#!/bin/bash
if $(which apt >/dev/null); then
  sudo apt update
  sudo apt install -y neovim zsh autojump dstat pg-activity stow cargo asciinema ncdu
fi

set -e

stow -t ~/ zsh
stow -t ~/ git
stow -t ~/ bash

# Install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Change default shell to zsh
sudo chsh -s $(which zsh) $USER

